name: DigitecToolAPI Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'DigitecToolAPI/**'
      - '.github/workflows/WebAPI.yml'

jobs:
  build_docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: docker build -f DigitecToolAPI/Dockerfile -t digitecapibuild:$(git rev-parse --short "$GITHUB_SHA") .

      - name: Save Docker image to tarball
        run: docker save digitecapibuild:$(git rev-parse --short "$GITHUB_SHA") -o /tmp/digitecapibuild.tar

  deploy:
    runs-on: self-hosted
    needs: build_docker

    steps:
      - name: Load Docker image from tarball
        run: docker load -i /tmp/digitecapibuild.tar

      - name: Remove old docker container
        run: |
          CONTAINER_NAME=DigitecToolAPI
          RUNNING=$(docker ps -q --filter name=$CONTAINER_NAME)
          if [ -n "$RUNNING" ]; then
            docker stop $CONTAINER_NAME
          fi

      - name: Remove previous container (if exists)
        run: |
          CONTAINER_NAME=DigitecToolAPI
          EXISTING=$(docker ps -aq --filter name=$CONTAINER_NAME)
          if [ -n "$EXISTING" ]; then
            docker rm $EXISTING
          fi

      - name: Deploy new container
        run: |
          CONTAINER_NAME=DigitecToolAPI
          docker run -d -p 310:80 -p 311:443 --name $CONTAINER_NAME digitecapibuild:$(git rev-parse --short "$GITHUB_SHA")
